FLAGS = g++ -g -std=c++17 -Wall -Wextra -Werror
SOURCES = Graph/*.cpp GraphAlgorithms/*.cpp DotFormatHandler/*.cpp DataStructures/Matrix/*.cpp \
			DataStructures/Stack/*.cpp DataStructures/Queue/*.cpp ConsoleEngine/*.cpp

kek:
	$(FLAGS) $(SOURCES) -o app.out
	./app.out